name: Rust

on: [push, pull_request]

jobs:
  build:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
          - target: x86_64-apple-darwin
            archive: zip
    steps:
      - uses: actions/checkout@master
      - name: Temporarily modify the rust toolchain version
        run: rustup update nightly && rustup default nightly
      - name: Compile and release
        run: |
          cargo build --release --target ${{ matrix.target }}
          mkdir -p target/${{ matrix.target }}/release
          cp target/${{ matrix.target }}/release/convert-texture-o2r target/${{ matrix.target }}/release/convert-texture-o2r-${{ matrix.target }}
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: convert-texture-o2r-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/convert-texture-o2r-${{ matrix.target }}
